### ISSUE TITLE
System Property serverPort is ignored

### ISSUE THREAD

**Issue by gcase** [kennedyoliveira/standalone-hystrix-dashboard#1]
According to the documentation:

```
java -jar -DserverPort=8080 standalone-hystrix-dashboard-1.5.2-all.jar
```

should launch the server on port 8080.  However, it starts on the default `7979` instead.  I did some digging into vertx documentation and was able to find a workaround:

Create a `hystrix.conf` file with the following contents:

``` javascript
{
  "serverPort": 8080
}
```

Then this will start the server on the port 8080 as desired.

```
java -jar standalone-hystrix-dashboard-1.5.2-all.jar -conf hystrix.conf 
```

**Comment by kennedyoliveira** [comment]
@gcase, i refactored the verticle and forgot to add the system property, just fixed it

**Comment by kennedyoliveira** [comment]
@gcase, released a new version following the netflix release, with the correction!
