### ISSUE TITLE
Available on Maven Central Repository?

### ISSUE THREAD

**Issue by shou1dwe** [kennedyoliveira/standalone-hystrix-dashboard#2]
Currently, the dependency is only available through this repository. May I know whether there is getting it up on the central repository?
https://bintray.com/kennedyoliveira/maven/standalone-hystrix-dashboard/view

**Comment by kennedyoliveira** [comment]
Hello @shou1dwe!

I tried to upload it on maven and had some problems, but i don't remember which one, i'll try again and get back at you with the feedback.

For curiosity, what is your use case that you need it on Central?

**Comment by shou1dwe** [comment]
It is the evil corporate firewall :p Maven Central Repository is already whitelisted, so as far as I know thats the only public maven repository that we have access behind the firewall. I guess the same problem should be there for many companies.

**Comment by kennedyoliveira** [comment]
ahh the firewall haha, sorry for the delay, really busy at work, i just released a new version and will try to upload it on maven central, was missing a source jar, i'm waiting on bintray that i use to sync, when it get available i'll notify you.

**Comment by kennedyoliveira** [comment]
@shou1dwe, just made it to maven central! It probably will take 1 to 2 hours to be there, so check if later!

**Comment by shou1dwe** [comment]
Hey, it looks perfectly fine btw. Thank you very much!

**Comment by kennedyoliveira** [comment]
Your welcome, @shou1dwe! I'm glad to help :)
